services:
  vector_db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_vector_db
    ports:
      - "8001:8000"  
    volumes:
      - chroma_data:/data

  api:
    build: .
    container_name: langchain_api
    image: langchain_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vector_db
    volumes:
      - ./src:/app/src

volumes:
  chroma_data:
