services:
  vector_db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_vector_db
    ports:
      - "8001:8000"  
    volumes:
      - chroma_data:/data

  langchain_api:
    build: .
    container_name: langchain_api
    image: langchain_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vector_db
    volumes:
      - ./src:/app/src
      - .:/app
    command: uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - ENV=dev
  
  notebook:
    build: .
    volumes:
      - .:/app
    working_dir: /app/notebooks
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

volumes:
  chroma_data:
