# LLM Provider Configuration
openai:
  api_key: "${OPENAI_API_KEY}"
  base_url: "https://api.openai.com/v1"
  default_models:
    - "gpt-4.1-nano"
    - "gpt-3.5-turbo"
    - "gpt-4"
    - "gpt-4-turbo"

anthropic:
  api_key: "${ANTHROPIC_API_KEY}"
  base_url: null
  default_models:
    - "claude-3-sonnet-20240229"
    - "claude-3-haiku-20240307"
    - "claude-3-opus-20240229"

openrouter:
  api_key: "${OPENROUTER_API_KEY}"
  base_url: "https://openrouter.ai/api/v1"
  default_models:
    - "mistralai/mistral-7b-instruct:free"
    - "anthropic/claude-3-haiku"
    - "openai/gpt-3.5-turbo"
    - "meta-llama/llama-2-7b-chat"

# Model aliases for easier usage
model_aliases:
  gpt4: "gpt-4.1-nano"
  gpt3: "gpt-3.5-turbo"
  claude: "claude-3-sonnet-20240229"
  claude-fast: "claude-3-haiku-20240307"
  mistral: "mistralai/mistral-7b-instruct:free"
  llama: "meta-llama/llama-2-7b-chat"